name: CommandGUI
version: 1.2.2
api-version: 1.13
main: de.jatitv.commandgui.system.Main
authors: [ JaTiTV ]
softdepend:
  - Vault
  - Economy
  - EssentialsX
  - CMI
  - PlaceholderAPI
commands:
  commandgui:
    description: Open the CGUI
    aliases: [cgui]

permissions:
  commandgui.command:
    default: op
  commandgui.command.info:
    default: op
  commandgui.command.give:
    default: op
  commandgui.admin:
    default: op
