name: CommandGUI
version: ${project.version}
api-version: 1.13
main: de.jatitv.commandgui.system.Main
authors: [ JaTiTV ]
softdepend:
  - Vault
  - NBTAPI
  - Economy
  - EssentialsX
  - CMI
  - PlaceholderAPI
commands:
  commandgui:
    description: Open the CGUI
    aliases: [cgui]


permissions:
  # Haupt Permission
  commandgui.command:
    default: op

  # Admin Permissions
  commandgui.command.info:
    default: op
  commandgui.command.give:
    default: op
  commandgui.admin:
    default: op

  # Gui Command Permissions
  commandgui.command.gui1:
    default: op
  commandgui.command.gui2:
    default: op
  commandgui.command.gui3:
    default: op


  # Give UseItem On First Join Permissions
  commandgui.giveuseitemonfirstjoin.gui1:
    default: op
  commandgui.giveuseitemonfirstjoin.gui2:
    default: op
  commandgui.giveuseitemonfirstjoin.gui3:
    default: op

  # Use GUI Permissions
  commandgui.use.gui1:
    default: op
  commandgui.use.gui2:
    default: op
  commandgui.use.gui3:
    default: op

  # Slot Permissions GUI 1
  commandgui.use.gui1.line1.slot1:
    default: op
  commandgui.use.gui1.line1.slot2:
    default: op
  commandgui.use.gui1.line1.slot3:
    default: op
  commandgui.use.gui1.line1.slot4:
    default: op
  commandgui.use.gui1.line1.slot5:
    default: op
  commandgui.use.gui1.line1.slot6:
    default: op
  commandgui.use.gui1.line1.slot7:
    default: op
  commandgui.use.gui1.line1.slot8:
    default: op
  commandgui.use.gui1.line1.slot9:
    default: op
  commandgui.use.gui1.line2.slot1:
    default: op
  commandgui.use.gui1.line2.slot2:
    default: op
  commandgui.use.gui1.line2.slot3:
    default: op
  commandgui.use.gui1.line2.slot4:
    default: op
  commandgui.use.gui1.line2.slot5:
    default: op
  commandgui.use.gui1.line2.slot6:
    default: op
  commandgui.use.gui1.line2.slot7:
    default: op
  commandgui.use.gui1.line2.slot8:
    default: op
  commandgui.use.gui1.line2.slot9:
    default: op
  commandgui.use.gui1.line3.slot1:
    default: op
  commandgui.use.gui1.line3.slot2:
    default: op
  commandgui.use.gui1.line3.slot3:
    default: op
  commandgui.use.gui1.line3.slot4:
    default: op
  commandgui.use.gui1.line3.slot5:
    default: op
  commandgui.use.gui1.line3.slot6:
    default: op
  commandgui.use.gui1.line3.slot7:
    default: op
  commandgui.use.gui1.line3.slot8:
    default: op
  commandgui.use.gui1.line3.slot9:
    default: op
  commandgui.use.gui1.line4.slot1:
    default: op
  commandgui.use.gui1.line4.slot2:
    default: op
  commandgui.use.gui1.line4.slot3:
    default: op
  commandgui.use.gui1.line4.slot4:
    default: op
  commandgui.use.gui1.line4.slot5:
    default: op
  commandgui.use.gui1.line4.slot6:
    default: op
  commandgui.use.gui1.line4.slot7:
    default: op
  commandgui.use.gui1.line4.slot8:
    default: op
  commandgui.use.gui1.line4.slot9:
    default: op
  commandgui.use.gui1.line5.slot1:
    default: op
  commandgui.use.gui1.line5.slot2:
    default: op
  commandgui.use.gui1.line5.slot3:
    default: op
  commandgui.use.gui1.line5.slot4:
    default: op
  commandgui.use.gui1.line5.slot5:
    default: op
  commandgui.use.gui1.line5.slot6:
    default: op
  commandgui.use.gui1.line5.slot7:
    default: op
  commandgui.use.gui1.line5.slot8:
    default: op
  commandgui.use.gui1.line5.slot9:
    default: op
  commandgui.use.gui1.line6.slot1:
    default: op
  commandgui.use.gui1.line6.slot2:
    default: op
  commandgui.use.gui1.line6.slot3:
    default: op
  commandgui.use.gui1.line6.slot4:
    default: op
  commandgui.use.gui1.line6.slot5:
    default: op
  commandgui.use.gui1.line6.slot6:
    default: op
  commandgui.use.gui1.line6.slot7:
    default: op
  commandgui.use.gui1.line6.slot8:
    default: op
  commandgui.use.gui1.line6.slot9:
    default: op
  commandgui.use.gui1.line7.slot1:
    default: op
  commandgui.use.gui1.line7.slot2:
    default: op
  commandgui.use.gui1.line7.slot3:
    default: op
  commandgui.use.gui1.line7.slot4:
    default: op
  commandgui.use.gui1.line7.slot5:
    default: op
  commandgui.use.gui1.line7.slot6:
    default: op
  commandgui.use.gui1.line7.slot7:
    default: op
  commandgui.use.gui1.line7.slot8:
    default: op
  commandgui.use.gui1.line7.slot9:
    default: op
  commandgui.use.gui1.line8.slot1:
    default: op
  commandgui.use.gui1.line8.slot2:
    default: op
  commandgui.use.gui1.line8.slot3:
    default: op
  commandgui.use.gui1.line8.slot4:
    default: op
  commandgui.use.gui1.line8.slot5:
    default: op
  commandgui.use.gui1.line8.slot6:
    default: op
  commandgui.use.gui1.line8.slot7:
    default: op
  commandgui.use.gui1.line8.slot8:
    default: op
  commandgui.use.gui1.line8.slot9:
    default: op
  commandgui.use.gui1.line9.slot1:
    default: op
  commandgui.use.gui1.line9.slot2:
    default: op
  commandgui.use.gui1.line9.slot3:
    default: op
  commandgui.use.gui1.line9.slot4:
    default: op
  commandgui.use.gui1.line9.slot5:
    default: op
  commandgui.use.gui1.line9.slot6:
    default: op
  commandgui.use.gui1.line9.slot7:
    default: op
  commandgui.use.gui1.line9.slot8:
    default: op
  commandgui.use.gui1.line9.slot9:
    default: op

  # Slot Permissions GUI 2
  commandgui.use.gui2.line1.slot1:
    default: op
  commandgui.use.gui2.line1.slot2:
    default: op
  commandgui.use.gui2.line1.slot3:
    default: op
  commandgui.use.gui2.line1.slot4:
    default: op
  commandgui.use.gui2.line1.slot5:
    default: op
  commandgui.use.gui2.line1.slot6:
    default: op
  commandgui.use.gui2.line1.slot7:
    default: op
  commandgui.use.gui2.line1.slot8:
    default: op
  commandgui.use.gui2.line1.slot9:
    default: op
  commandgui.use.gui2.line2.slot1:
    default: op
  commandgui.use.gui2.line2.slot2:
    default: op
  commandgui.use.gui2.line2.slot3:
    default: op
  commandgui.use.gui2.line2.slot4:
    default: op
  commandgui.use.gui2.line2.slot5:
    default: op
  commandgui.use.gui2.line2.slot6:
    default: op
  commandgui.use.gui2.line2.slot7:
    default: op
  commandgui.use.gui2.line2.slot8:
    default: op
  commandgui.use.gui2.line2.slot9:
    default: op
  commandgui.use.gui2.line3.slot1:
    default: op
  commandgui.use.gui2.line3.slot2:
    default: op
  commandgui.use.gui2.line3.slot3:
    default: op
  commandgui.use.gui2.line3.slot4:
    default: op
  commandgui.use.gui2.line3.slot5:
    default: op
  commandgui.use.gui2.line3.slot6:
    default: op
  commandgui.use.gui2.line3.slot7:
    default: op
  commandgui.use.gui2.line3.slot8:
    default: op
  commandgui.use.gui2.line3.slot9:
    default: op
  commandgui.use.gui2.line4.slot1:
    default: op
  commandgui.use.gui2.line4.slot2:
    default: op
  commandgui.use.gui2.line4.slot3:
    default: op
  commandgui.use.gui2.line4.slot4:
    default: op
  commandgui.use.gui2.line4.slot5:
    default: op
  commandgui.use.gui2.line4.slot6:
    default: op
  commandgui.use.gui2.line4.slot7:
    default: op
  commandgui.use.gui2.line4.slot8:
    default: op
  commandgui.use.gui2.line4.slot9:
    default: op
  commandgui.use.gui2.line5.slot1:
    default: op
  commandgui.use.gui2.line5.slot2:
    default: op
  commandgui.use.gui2.line5.slot3:
    default: op
  commandgui.use.gui2.line5.slot4:
    default: op
  commandgui.use.gui2.line5.slot5:
    default: op
  commandgui.use.gui2.line5.slot6:
    default: op
  commandgui.use.gui2.line5.slot7:
    default: op
  commandgui.use.gui2.line5.slot8:
    default: op
  commandgui.use.gui2.line5.slot9:
    default: op
  commandgui.use.gui2.line6.slot1:
    default: op
  commandgui.use.gui2.line6.slot2:
    default: op
  commandgui.use.gui2.line6.slot3:
    default: op
  commandgui.use.gui2.line6.slot4:
    default: op
  commandgui.use.gui2.line6.slot5:
    default: op
  commandgui.use.gui2.line6.slot6:
    default: op
  commandgui.use.gui2.line6.slot7:
    default: op
  commandgui.use.gui2.line6.slot8:
    default: op
  commandgui.use.gui2.line6.slot9:
    default: op
  commandgui.use.gui2.line7.slot1:
    default: op
  commandgui.use.gui2.line7.slot2:
    default: op
  commandgui.use.gui2.line7.slot3:
    default: op
  commandgui.use.gui2.line7.slot4:
    default: op
  commandgui.use.gui2.line7.slot5:
    default: op
  commandgui.use.gui2.line7.slot6:
    default: op
  commandgui.use.gui2.line7.slot7:
    default: op
  commandgui.use.gui2.line7.slot8:
    default: op
  commandgui.use.gui2.line7.slot9:
    default: op
  commandgui.use.gui2.line8.slot1:
    default: op
  commandgui.use.gui2.line8.slot2:
    default: op
  commandgui.use.gui2.line8.slot3:
    default: op
  commandgui.use.gui2.line8.slot4:
    default: op
  commandgui.use.gui2.line8.slot5:
    default: op
  commandgui.use.gui2.line8.slot6:
    default: op
  commandgui.use.gui2.line8.slot7:
    default: op
  commandgui.use.gui2.line8.slot8:
    default: op
  commandgui.use.gui2.line8.slot9:
    default: op
  commandgui.use.gui2.line9.slot1:
    default: op
  commandgui.use.gui2.line9.slot2:
    default: op
  commandgui.use.gui2.line9.slot3:
    default: op
  commandgui.use.gui2.line9.slot4:
    default: op
  commandgui.use.gui2.line9.slot5:
    default: op
  commandgui.use.gui2.line9.slot6:
    default: op
  commandgui.use.gui2.line9.slot7:
    default: op
  commandgui.use.gui2.line9.slot8:
    default: op
  commandgui.use.gui2.line9.slot9:
    default: op

  # Slot Permissions GUI 3
  commandgui.use.gui3.line1.slot1:
    default: op
  commandgui.use.gui3.line1.slot2:
    default: op
  commandgui.use.gui3.line1.slot3:
    default: op
  commandgui.use.gui3.line1.slot4:
    default: op
  commandgui.use.gui3.line1.slot5:
    default: op
  commandgui.use.gui3.line1.slot6:
    default: op
  commandgui.use.gui3.line1.slot7:
    default: op
  commandgui.use.gui3.line1.slot8:
    default: op
  commandgui.use.gui3.line1.slot9:
    default: op
  commandgui.use.gui3.line2.slot1:
    default: op
  commandgui.use.gui3.line2.slot2:
    default: op
  commandgui.use.gui3.line2.slot3:
    default: op
  commandgui.use.gui3.line2.slot4:
    default: op
  commandgui.use.gui3.line2.slot5:
    default: op
  commandgui.use.gui3.line2.slot6:
    default: op
  commandgui.use.gui3.line2.slot7:
    default: op
  commandgui.use.gui3.line2.slot8:
    default: op
  commandgui.use.gui3.line2.slot9:
    default: op
  commandgui.use.gui3.line3.slot1:
    default: op
  commandgui.use.gui3.line3.slot2:
    default: op
  commandgui.use.gui3.line3.slot3:
    default: op
  commandgui.use.gui3.line3.slot4:
    default: op
  commandgui.use.gui3.line3.slot5:
    default: op
  commandgui.use.gui3.line3.slot6:
    default: op
  commandgui.use.gui3.line3.slot7:
    default: op
  commandgui.use.gui3.line3.slot8:
    default: op
  commandgui.use.gui3.line3.slot9:
    default: op
  commandgui.use.gui3.line4.slot1:
    default: op
  commandgui.use.gui3.line4.slot2:
    default: op
  commandgui.use.gui3.line4.slot3:
    default: op
  commandgui.use.gui3.line4.slot4:
    default: op
  commandgui.use.gui3.line4.slot5:
    default: op
  commandgui.use.gui3.line4.slot6:
    default: op
  commandgui.use.gui3.line4.slot7:
    default: op
  commandgui.use.gui3.line4.slot8:
    default: op
  commandgui.use.gui3.line4.slot9:
    default: op
  commandgui.use.gui3.line5.slot1:
    default: op
  commandgui.use.gui3.line5.slot2:
    default: op
  commandgui.use.gui3.line5.slot3:
    default: op
  commandgui.use.gui3.line5.slot4:
    default: op
  commandgui.use.gui3.line5.slot5:
    default: op
  commandgui.use.gui3.line5.slot6:
    default: op
  commandgui.use.gui3.line5.slot7:
    default: op
  commandgui.use.gui3.line5.slot8:
    default: op
  commandgui.use.gui3.line5.slot9:
    default: op
  commandgui.use.gui3.line6.slot1:
    default: op
  commandgui.use.gui3.line6.slot2:
    default: op
  commandgui.use.gui3.line6.slot3:
    default: op
  commandgui.use.gui3.line6.slot4:
    default: op
  commandgui.use.gui3.line6.slot5:
    default: op
  commandgui.use.gui3.line6.slot6:
    default: op
  commandgui.use.gui3.line6.slot7:
    default: op
  commandgui.use.gui3.line6.slot8:
    default: op
  commandgui.use.gui3.line6.slot9:
    default: op
  commandgui.use.gui3.line7.slot1:
    default: op
  commandgui.use.gui3.line7.slot2:
    default: op
  commandgui.use.gui3.line7.slot3:
    default: op
  commandgui.use.gui3.line7.slot4:
    default: op
  commandgui.use.gui3.line7.slot5:
    default: op
  commandgui.use.gui3.line7.slot6:
    default: op
  commandgui.use.gui3.line7.slot7:
    default: op
  commandgui.use.gui3.line7.slot8:
    default: op
  commandgui.use.gui3.line7.slot9:
    default: op
  commandgui.use.gui3.line8.slot1:
    default: op
  commandgui.use.gui3.line8.slot2:
    default: op
  commandgui.use.gui3.line8.slot3:
    default: op
  commandgui.use.gui3.line8.slot4:
    default: op
  commandgui.use.gui3.line8.slot5:
    default: op
  commandgui.use.gui3.line8.slot6:
    default: op
  commandgui.use.gui3.line8.slot7:
    default: op
  commandgui.use.gui3.line8.slot8:
    default: op
  commandgui.use.gui3.line8.slot9:
    default: op
  commandgui.use.gui3.line9.slot1:
    default: op
  commandgui.use.gui3.line9.slot2:
    default: op
  commandgui.use.gui3.line9.slot3:
    default: op
  commandgui.use.gui3.line9.slot4:
    default: op
  commandgui.use.gui3.line9.slot5:
    default: op
  commandgui.use.gui3.line9.slot6:
    default: op
  commandgui.use.gui3.line9.slot7:
    default: op
  commandgui.use.gui3.line9.slot8:
    default: op
  commandgui.use.gui3.line9.slot9:
    default: op