GUI:
  Enable: true
  Lines: 1
  Name: '&5default &9GUI'
  FillItem:
    Enable: true
    Item: BLACK_STAINED_GLASS_PANE
Command:
  Alias: true
  Permission:
    Required: true
Slots:
  Example:
    Slot: 5
    Enable: true
    Item:
      Empty: false
      Amount: 1
      PlayerHead:
        Enable: true
        Base64:
          Enable: true
          Base64Value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzg3M2MxMmJmZmI1MjUxYTBiODhkNWFlNzVjNzI0N2NiMzlhNzVmZjFhODFjYmU0YzhhMzliMzExZGRlZGEifX19
        PlayerWhoHasOpenedTheGUI: false
        PlayerName: ''
      Material: ''
      Name: '&3Support Discord'
      Lore:
        - '&8-----------------'
        - '&bIf you need help setting up the plugin,'
        - '&bfeel free to contact me on the Suport Discord.'
        - '&8-----------------'
        - '&eIf you find any errors or bugs,'
        - '&eplease contact me so I can fix them.'
        - '&8-----------------'
        - '&5Discord: ยง7https://discord.gg/vRyXFFterJ'
    CustomSound:
      Enable: false
      NoSound: false
      Sound: ''
    Cost:
      Enable: false
      Price: 0.0
    Command:
      Enable: false
      BungeeCommand: false
      CommandAsConsole: false
      Command:
        - ''
    OpenGUI:
      Enable: false
      GUI: ''
    Message:
      Enable: true
      Message:
        - '&6You can find more information on Discord: &ehttps://discord.gg/vRyXFFterJ'
    Permission:
      Required: false
    ServerChange:
      Enable: false
      Server: ''
    SetConfig:
      Enable: false
      File:
        Path: ''
      Option:
        Path: ''
        Premat: String
      Value:
        LeftClick:
          ChatInput: false
          String: ''
          Boolean: false
          Integer: 0
          Double: 0.0
          List: []
        RightClick:
          ChatInput: false
          String: ''
          Boolean: false
          Integer: 0
          Double: 0.0
          List: []
      PluginReload:
        Enable: false
        Command: ''