name: CommandGUI
version: 2.0-SNAPSHOT
main: de.jatitv.commandgui.system.Main
api-version: 1.16
authors: [ JaTiTV ]
softdepend:
    - Vault
    - NBTAPI
    - Economy
    - EssentialsX
    - CMI
commands:
  commandgui:
    description: Open the CGUI
  cgui:
    description: Open the CGUI

permissions:
  commandgui.command:
    default: op

  commandgui.command.info:
    default: op

  commandgui.admin:
    default: op

